fail_fast: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-json
        exclude: .vscode
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: mixed-line-ending
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-symlinks
      - id: check-byte-order-marker
        name: 'check BOM - deprecated: use fix-byte-order-marker'

-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v16.0.2'
    hooks:
      - id: clang-format
        exclude_types: [javascript, json]


- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.32.2
  hooks:
    - id: markdownlint
      args: ["--fix"]
